// Code generated by "stringer -type=Estado"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pendiente-0]
	_ = x[EnProceso-1]
	_ = x[Completado-2]
	_ = x[Cancelado-3]
}

const _Estado_name = "PendienteEnProcesoCompletadoCancelado"

var _Estado_index = [...]uint8{0, 9, 18, 28, 37}

func (i Estado) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Estado_index)-1 {
		return "Estado(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Estado_name[_Estado_index[idx]:_Estado_index[idx+1]]
}
