// Code generated by gen/main.go from paises.csv; DO NOT EDIT.

package main

// CodigoPais es un código ISO 3166-1 alfa-2.
type CodigoPais string

const (
	PaisAR CodigoPais = "AR" // Argentina
	PaisCL CodigoPais = "CL" // Chile
	PaisCO CodigoPais = "CO" // Colombia
	PaisES CodigoPais = "ES" // España
	PaisMX CodigoPais = "MX" // México
	PaisPE CodigoPais = "PE" // Perú
	PaisUY CodigoPais = "UY" // Uruguay
)

// InfoPais contiene los datos de un país.
type InfoPais struct {
	Nombre  string
	Moneda  string
	Prefijo string
}

var paises = map[CodigoPais]InfoPais{
	PaisAR: {Nombre: "Argentina", Moneda: "ARS", Prefijo: "+54"},
	PaisCL: {Nombre: "Chile", Moneda: "CLP", Prefijo: "+56"},
	PaisCO: {Nombre: "Colombia", Moneda: "COP", Prefijo: "+57"},
	PaisES: {Nombre: "España", Moneda: "EUR", Prefijo: "+34"},
	PaisMX: {Nombre: "México", Moneda: "MXN", Prefijo: "+52"},
	PaisPE: {Nombre: "Perú", Moneda: "PEN", Prefijo: "+51"},
	PaisUY: {Nombre: "Uruguay", Moneda: "UYU", Prefijo: "+598"},
}

// TodosLosPaises devuelve los códigos en el orden del archivo fuente.
func TodosLosPaises() []CodigoPais {
	return []CodigoPais{PaisAR, PaisCL, PaisCO, PaisES, PaisMX, PaisPE, PaisUY}
}

// Info devuelve los datos del país y si el código existe.
func (c CodigoPais) Info() (InfoPais, bool) {
	p, ok := paises[c]
	return p, ok
}
