// Code generated by "stringer -type=Prioridad -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Baja-1]
	_ = x[Media-2]
	_ = x[Alta-3]
	_ = x[Critica-4]
}

const _Prioridad_name = "bajamedia¡alta!CRÍTICA"

var _Prioridad_index = [...]uint8{0, 4, 9, 16, 24}

func (i Prioridad) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Prioridad_index)-1 {
		return "Prioridad(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Prioridad_name[_Prioridad_index[idx]:_Prioridad_index[idx+1]]
}
