// Definición del servicio para el tema 43.
// A partir de este archivo protoc (o buf) genera el código Go en ../catalogopb.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: catalogo.proto

package catalogopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Catalogo_ObtenerProducto_FullMethodName = "/catalogo.v1.Catalogo/ObtenerProducto"
	Catalogo_CrearProducto_FullMethodName   = "/catalogo.v1.Catalogo/CrearProducto"
	Catalogo_ListarProductos_FullMethodName = "/catalogo.v1.Catalogo/ListarProductos"
	Catalogo_Comprar_FullMethodName         = "/catalogo.v1.Catalogo/Comprar"
)

// CatalogoClient is the client API for Catalogo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogoClient interface {
	// Unario: un request, una respuesta (como una función normal)
	ObtenerProducto(ctx context.Context, in *ObtenerProductoRequest, opts ...grpc.CallOption) (*Producto, error)
	CrearProducto(ctx context.Context, in *CrearProductoRequest, opts ...grpc.CallOption) (*Producto, error)
	// Streaming del servidor: un request, muchas respuestas
	ListarProductos(ctx context.Context, in *ListarProductosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Producto], error)
	// Streaming del cliente: muchos requests, una respuesta
	Comprar(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ItemCompra, ResumenCompra], error)
}

type catalogoClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogoClient(cc grpc.ClientConnInterface) CatalogoClient {
	return &catalogoClient{cc}
}

func (c *catalogoClient) ObtenerProducto(ctx context.Context, in *ObtenerProductoRequest, opts ...grpc.CallOption) (*Producto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Producto)
	err := c.cc.Invoke(ctx, Catalogo_ObtenerProducto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogoClient) CrearProducto(ctx context.Context, in *CrearProductoRequest, opts ...grpc.CallOption) (*Producto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Producto)
	err := c.cc.Invoke(ctx, Catalogo_CrearProducto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogoClient) ListarProductos(ctx context.Context, in *ListarProductosRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Producto], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Catalogo_ServiceDesc.Streams[0], Catalogo_ListarProductos_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListarProductosRequest, Producto]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Catalogo_ListarProductosClient = grpc.ServerStreamingClient[Producto]

func (c *catalogoClient) Comprar(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ItemCompra, ResumenCompra], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Catalogo_ServiceDesc.Streams[1], Catalogo_Comprar_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ItemCompra, ResumenCompra]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Catalogo_ComprarClient = grpc.ClientStreamingClient[ItemCompra, ResumenCompra]

// CatalogoServer is the server API for Catalogo service.
// All implementations must embed UnimplementedCatalogoServer
// for forward compatibility.
type CatalogoServer interface {
	// Unario: un request, una respuesta (como una función normal)
	ObtenerProducto(context.Context, *ObtenerProductoRequest) (*Producto, error)
	CrearProducto(context.Context, *CrearProductoRequest) (*Producto, error)
	// Streaming del servidor: un request, muchas respuestas
	ListarProductos(*ListarProductosRequest, grpc.ServerStreamingServer[Producto]) error
	// Streaming del cliente: muchos requests, una respuesta
	Comprar(grpc.ClientStreamingServer[ItemCompra, ResumenCompra]) error
	mustEmbedUnimplementedCatalogoServer()
}

// UnimplementedCatalogoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogoServer struct{}

func (UnimplementedCatalogoServer) ObtenerProducto(context.Context, *ObtenerProductoRequest) (*Producto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerProducto not implemented")
}
func (UnimplementedCatalogoServer) CrearProducto(context.Context, *CrearProductoRequest) (*Producto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrearProducto not implemented")
}
func (UnimplementedCatalogoServer) ListarProductos(*ListarProductosRequest, grpc.ServerStreamingServer[Producto]) error {
	return status.Errorf(codes.Unimplemented, "method ListarProductos not implemented")
}
func (UnimplementedCatalogoServer) Comprar(grpc.ClientStreamingServer[ItemCompra, ResumenCompra]) error {
	return status.Errorf(codes.Unimplemented, "method Comprar not implemented")
}
func (UnimplementedCatalogoServer) mustEmbedUnimplementedCatalogoServer() {}
func (UnimplementedCatalogoServer) testEmbeddedByValue()                  {}

// UnsafeCatalogoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogoServer will
// result in compilation errors.
type UnsafeCatalogoServer interface {
	mustEmbedUnimplementedCatalogoServer()
}

func RegisterCatalogoServer(s grpc.ServiceRegistrar, srv CatalogoServer) {
	// If the following call pancis, it indicates UnimplementedCatalogoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Catalogo_ServiceDesc, srv)
}

func _Catalogo_ObtenerProducto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerProductoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogoServer).ObtenerProducto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalogo_ObtenerProducto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogoServer).ObtenerProducto(ctx, req.(*ObtenerProductoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalogo_CrearProducto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearProductoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogoServer).CrearProducto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalogo_CrearProducto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogoServer).CrearProducto(ctx, req.(*CrearProductoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalogo_ListarProductos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListarProductosRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatalogoServer).ListarProductos(m, &grpc.GenericServerStream[ListarProductosRequest, Producto]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Catalogo_ListarProductosServer = grpc.ServerStreamingServer[Producto]

func _Catalogo_Comprar_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CatalogoServer).Comprar(&grpc.GenericServerStream[ItemCompra, ResumenCompra]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Catalogo_ComprarServer = grpc.ClientStreamingServer[ItemCompra, ResumenCompra]

// Catalogo_ServiceDesc is the grpc.ServiceDesc for Catalogo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Catalogo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalogo.v1.Catalogo",
	HandlerType: (*CatalogoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ObtenerProducto",
			Handler:    _Catalogo_ObtenerProducto_Handler,
		},
		{
			MethodName: "CrearProducto",
			Handler:    _Catalogo_CrearProducto_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListarProductos",
			Handler:       _Catalogo_ListarProductos_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Comprar",
			Handler:       _Catalogo_Comprar_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "catalogo.proto",
}
