// Definición del servicio para el tema 43.
// A partir de este archivo protoc (o buf) genera el código Go en ../catalogopb.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: catalogo.proto

package catalogopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Categoria int32

const (
	Categoria_CATEGORIA_SIN_ESPECIFICAR Categoria = 0 // proto3: el primer valor debe ser 0
	Categoria_CATEGORIA_LIBROS          Categoria = 1
	Categoria_CATEGORIA_ELECTRONICA     Categoria = 2
)

// Enum value maps for Categoria.
var (
	Categoria_name = map[int32]string{
		0: "CATEGORIA_SIN_ESPECIFICAR",
		1: "CATEGORIA_LIBROS",
		2: "CATEGORIA_ELECTRONICA",
	}
	Categoria_value = map[string]int32{
		"CATEGORIA_SIN_ESPECIFICAR": 0,
		"CATEGORIA_LIBROS":          1,
		"CATEGORIA_ELECTRONICA":     2,
	}
)

func (x Categoria) Enum() *Categoria {
	p := new(Categoria)
	*p = x
	return p
}

func (x Categoria) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Categoria) Descriptor() protoreflect.EnumDescriptor {
	return file_catalogo_proto_enumTypes[0].Descriptor()
}

func (Categoria) Type() protoreflect.EnumType {
	return &file_catalogo_proto_enumTypes[0]
}

func (x Categoria) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Categoria.Descriptor instead.
func (Categoria) EnumDescriptor() ([]byte, []int) {
	return file_catalogo_proto_rawDescGZIP(), []int{0}
}

// Cada campo tiene un NÚMERO único: es lo que viaja en el binario, no el
// nombre. Nunca reutilices ni cambies el número de un campo ya publicado.
type Producto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Precio        float64                `protobuf:"fixed64,3,opt,name=precio,proto3" json:"precio,omitempty"`
	Etiquetas     []string               `protobuf:"bytes,4,rep,name=etiquetas,proto3" json:"etiquetas,omitempty"` // repeated = lista
	Categoria     Categoria              `protobuf:"varint,5,opt,name=categoria,proto3,enum=catalogo.v1.Categoria" json:"categoria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Producto) Reset() {
	*x = Producto{}
	mi := &file_catalogo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Producto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Producto) ProtoMessage() {}

func (x *Producto) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Producto.ProtoReflect.Descriptor instead.
func (*Producto) Descriptor() ([]byte, []int) {
	return file_catalogo_proto_rawDescGZIP(), []int{0}
}

func (x *Producto) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Producto) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Producto) GetPrecio() float64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Producto) GetEtiquetas() []string {
	if x != nil {
		return x.Etiquetas
	}
	return nil
}

func (x *Producto) GetCategoria() Categoria {
	if x != nil {
		return x.Categoria
	}
	return Categoria_CATEGORIA_SIN_ESPECIFICAR
}

type ObtenerProductoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerProductoRequest) Reset() {
	*x = ObtenerProductoRequest{}
	mi := &file_catalogo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerProductoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerProductoRequest) ProtoMessage() {}

func (x *ObtenerProductoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerProductoRequest.ProtoReflect.Descriptor instead.
func (*ObtenerProductoRequest) Descriptor() ([]byte, []int) {
	return file_catalogo_proto_rawDescGZIP(), []int{1}
}

func (x *ObtenerProductoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListarProductosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrecioMaximo  float64                `protobuf:"fixed64,1,opt,name=precio_maximo,json=precioMaximo,proto3" json:"precio_maximo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarProductosRequest) Reset() {
	*x = ListarProductosRequest{}
	mi := &file_catalogo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarProductosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarProductosRequest) ProtoMessage() {}

func (x *ListarProductosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarProductosRequest.ProtoReflect.Descriptor instead.
func (*ListarProductosRequest) Descriptor() ([]byte, []int) {
	return file_catalogo_proto_rawDescGZIP(), []int{2}
}

func (x *ListarProductosRequest) GetPrecioMaximo() float64 {
	if x != nil {
		return x.PrecioMaximo
	}
	return 0
}

type CrearProductoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Precio        float64                `protobuf:"fixed64,2,opt,name=precio,proto3" json:"precio,omitempty"`
	Etiquetas     []string               `protobuf:"bytes,3,rep,name=etiquetas,proto3" json:"etiquetas,omitempty"`
	Categoria     Categoria              `protobuf:"varint,4,opt,name=categoria,proto3,enum=catalogo.v1.Categoria" json:"categoria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearProductoRequest) Reset() {
	*x = CrearProductoRequest{}
	mi := &file_catalogo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearProductoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearProductoRequest) ProtoMessage() {}

func (x *CrearProductoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearProductoRequest.ProtoReflect.Descriptor instead.
func (*CrearProductoRequest) Descriptor() ([]byte, []int) {
	return file_catalogo_proto_rawDescGZIP(), []int{3}
}

func (x *CrearProductoRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CrearProductoRequest) GetPrecio() float64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *CrearProductoRequest) GetEtiquetas() []string {
	if x != nil {
		return x.Etiquetas
	}
	return nil
}

func (x *CrearProductoRequest) GetCategoria() Categoria {
	if x != nil {
		return x.Categoria
	}
	return Categoria_CATEGORIA_SIN_ESPECIFICAR
}

type ResumenCompra struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cantidad      int32                  `protobuf:"varint,1,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumenCompra) Reset() {
	*x = ResumenCompra{}
	mi := &file_catalogo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumenCompra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumenCompra) ProtoMessage() {}

func (x *ResumenCompra) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumenCompra.ProtoReflect.Descriptor instead.
func (*ResumenCompra) Descriptor() ([]byte, []int) {
	return file_catalogo_proto_rawDescGZIP(), []int{4}
}

func (x *ResumenCompra) GetCantidad() int32 {
	if x != nil {
		return x.Cantidad
	}
	return 0
}

func (x *ResumenCompra) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ItemCompra struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductoId    int32                  `protobuf:"varint,1,opt,name=producto_id,json=productoId,proto3" json:"producto_id,omitempty"`
	Unidades      int32                  `protobuf:"varint,2,opt,name=unidades,proto3" json:"unidades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemCompra) Reset() {
	*x = ItemCompra{}
	mi := &file_catalogo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemCompra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCompra) ProtoMessage() {}

func (x *ItemCompra) ProtoReflect() protoreflect.Message {
	mi := &file_catalogo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCompra.ProtoReflect.Descriptor instead.
func (*ItemCompra) Descriptor() ([]byte, []int) {
	return file_catalogo_proto_rawDescGZIP(), []int{5}
}

func (x *ItemCompra) GetProductoId() int32 {
	if x != nil {
		return x.ProductoId
	}
	return 0
}

func (x *ItemCompra) GetUnidades() int32 {
	if x != nil {
		return x.Unidades
	}
	return 0
}

var File_catalogo_proto protoreflect.FileDescriptor

const file_catalogo_proto_rawDesc = "" +
	"\n" +
	"\x0ecatalogo.proto\x12\vcatalogo.v1\"\x9e\x01\n" +
	"\bProducto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x16\n" +
	"\x06precio\x18\x03 \x01(\x01R\x06precio\x12\x1c\n" +
	"\tetiquetas\x18\x04 \x03(\tR\tetiquetas\x124\n" +
	"\tcategoria\x18\x05 \x01(\x0e2\x16.catalogo.v1.CategoriaR\tcategoria\"(\n" +
	"\x16ObtenerProductoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"=\n" +
	"\x16ListarProductosRequest\x12#\n" +
	"\rprecio_maximo\x18\x01 \x01(\x01R\fprecioMaximo\"\x9a\x01\n" +
	"\x14CrearProductoRequest\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12\x16\n" +
	"\x06precio\x18\x02 \x01(\x01R\x06precio\x12\x1c\n" +
	"\tetiquetas\x18\x03 \x03(\tR\tetiquetas\x124\n" +
	"\tcategoria\x18\x04 \x01(\x0e2\x16.catalogo.v1.CategoriaR\tcategoria\"A\n" +
	"\rResumenCompra\x12\x1a\n" +
	"\bcantidad\x18\x01 \x01(\x05R\bcantidad\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\"I\n" +
	"\n" +
	"ItemCompra\x12\x1f\n" +
	"\vproducto_id\x18\x01 \x01(\x05R\n" +
	"productoId\x12\x1a\n" +
	"\bunidades\x18\x02 \x01(\x05R\bunidades*[\n" +
	"\tCategoria\x12\x1d\n" +
	"\x19CATEGORIA_SIN_ESPECIFICAR\x10\x00\x12\x14\n" +
	"\x10CATEGORIA_LIBROS\x10\x01\x12\x19\n" +
	"\x15CATEGORIA_ELECTRONICA\x10\x022\xb7\x02\n" +
	"\bCatalogo\x12M\n" +
	"\x0fObtenerProducto\x12#.catalogo.v1.ObtenerProductoRequest\x1a\x15.catalogo.v1.Producto\x12I\n" +
	"\rCrearProducto\x12!.catalogo.v1.CrearProductoRequest\x1a\x15.catalogo.v1.Producto\x12O\n" +
	"\x0fListarProductos\x12#.catalogo.v1.ListarProductosRequest\x1a\x15.catalogo.v1.Producto0\x01\x12@\n" +
	"\aComprar\x12\x17.catalogo.v1.ItemCompra\x1a\x1a.catalogo.v1.ResumenCompra(\x01B\"Z golang-basico/43-grpc/catalogopbb\x06proto3"

var (
	file_catalogo_proto_rawDescOnce sync.Once
	file_catalogo_proto_rawDescData []byte
)

func file_catalogo_proto_rawDescGZIP() []byte {
	file_catalogo_proto_rawDescOnce.Do(func() {
		file_catalogo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalogo_proto_rawDesc), len(file_catalogo_proto_rawDesc)))
	})
	return file_catalogo_proto_rawDescData
}

var file_catalogo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_catalogo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_catalogo_proto_goTypes = []any{
	(Categoria)(0),                 // 0: catalogo.v1.Categoria
	(*Producto)(nil),               // 1: catalogo.v1.Producto
	(*ObtenerProductoRequest)(nil), // 2: catalogo.v1.ObtenerProductoRequest
	(*ListarProductosRequest)(nil), // 3: catalogo.v1.ListarProductosRequest
	(*CrearProductoRequest)(nil),   // 4: catalogo.v1.CrearProductoRequest
	(*ResumenCompra)(nil),          // 5: catalogo.v1.ResumenCompra
	(*ItemCompra)(nil),             // 6: catalogo.v1.ItemCompra
}
var file_catalogo_proto_depIdxs = []int32{
	0, // 0: catalogo.v1.Producto.categoria:type_name -> catalogo.v1.Categoria
	0, // 1: catalogo.v1.CrearProductoRequest.categoria:type_name -> catalogo.v1.Categoria
	2, // 2: catalogo.v1.Catalogo.ObtenerProducto:input_type -> catalogo.v1.ObtenerProductoRequest
	4, // 3: catalogo.v1.Catalogo.CrearProducto:input_type -> catalogo.v1.CrearProductoRequest
	3, // 4: catalogo.v1.Catalogo.ListarProductos:input_type -> catalogo.v1.ListarProductosRequest
	6, // 5: catalogo.v1.Catalogo.Comprar:input_type -> catalogo.v1.ItemCompra
	1, // 6: catalogo.v1.Catalogo.ObtenerProducto:output_type -> catalogo.v1.Producto
	1, // 7: catalogo.v1.Catalogo.CrearProducto:output_type -> catalogo.v1.Producto
	1, // 8: catalogo.v1.Catalogo.ListarProductos:output_type -> catalogo.v1.Producto
	5, // 9: catalogo.v1.Catalogo.Comprar:output_type -> catalogo.v1.ResumenCompra
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_catalogo_proto_init() }
func file_catalogo_proto_init() {
	if File_catalogo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalogo_proto_rawDesc), len(file_catalogo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalogo_proto_goTypes,
		DependencyIndexes: file_catalogo_proto_depIdxs,
		EnumInfos:         file_catalogo_proto_enumTypes,
		MessageInfos:      file_catalogo_proto_msgTypes,
	}.Build()
	File_catalogo_proto = out.File
	file_catalogo_proto_goTypes = nil
	file_catalogo_proto_depIdxs = nil
}
